# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8275688d847e92e64af0a949c9242609c95b93bc91cf93eb7d2d6130adec3616ea3acc10c63283f658cc378609d1a8bab0d45d0baf50d6fd9f3c50dd87abf0c1

test:
  secret_key_base: 0d972af869e1a9f3f0f52ba46167cf1b340a5ae41a06ff92a0b90503304634e182feb3dcea1fee416e4e0630cc034d9b5d390cae28aafc439ea5899e9ba0a86e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 3b7bd65c804fa87a3554bbf3a494a2879c70c206038d82bddb3e0b1ad94e4fc9d95edaa5546cbf2714d966c50798591620e66ca69d86b137a51080b4ac55029d

# secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
